import { buildBoard } from './board.ts';
const CONTRACT_VERSION = "factory-control-read-v0.1.1";
const ALLOWED_ORIGIN = "https://factory-control-web.juancho-dlfr.workers.dev";
const JSON_HEADERS={"Content-Type":"application/json","Cache-Control":"no-store"};
const MAX_AGENTS=200,MAX_WORK_ITEMS=200,MAX_HANDOFFS=2000,MAX_EVENTS=2000;
type Bucket={start:number,count:number};
const minuteBuckets=new Map<string,Bucket>(),burstBuckets=new Map<string,Bucket>();
const json=(body:unknown,status=200,extra:Record<string,string>={})=>new Response(JSON.stringify(body),{status,headers:{...JSON_HEADERS,...extra}});
const clean=(v:unknown,max=160)=>typeof v==="string"?v.replace(/[\r\n\t]+/g," ").slice(0,max):null;
const explicitTrue=(p:any,k:string)=>p?.[k]===true;
function cors(req:Request):Record<string,string>|null{const o=req.headers.get("origin");if(!o)return {};if(o!==ALLOWED_ORIGIN)return null;return {"Access-Control-Allow-Origin":o,"Vary":"Origin","Access-Control-Allow-Headers":"authorization,apikey,content-type","Access-Control-Allow-Methods":"GET,OPTIONS"};}
function env(){const url=Deno.env.get("SUPABASE_URL")??"",anon=Deno.env.get("SUPABASE_ANON_KEY")??Deno.env.get("SUPABASE_PUBLISHABLE_KEY")??"";const raw=Deno.env.get("SUPABASE_SECRET_KEYS");let service="";if(raw)try{service=JSON.parse(raw).default??""}catch{}service=service||Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!url||!anon)throw new Error("auth_backend_not_configured");return {url,anon,service};}
async function authenticateAdmin(req:Request){const auth=req.headers.get("authorization")??"";if(!auth.toLowerCase().startsWith("bearer "))return {ok:false,status:401,code:"UNAUTHENTICATED"} as const;const {url,anon}=env();const r=await fetch(`${url}/auth/v1/user`,{headers:{"Authorization":auth,"apikey":anon,"Accept":"application/json"}});if(!r.ok)return {ok:false,status:401,code:"UNAUTHENTICATED"} as const;const u=await r.json(),ids=new Set((Deno.env.get("FACTORY_CONTROL_ADMIN_USER_IDS")??"").split(",").map((x:string)=>x.trim()).filter(Boolean)),app=u?.app_metadata??{},roles=Array.isArray(app?.roles)?app.roles:[];const allowed=ids.has(String(u?.id??""))||app?.factory_control_admin===true||roles.includes("factory_control_admin");if(!allowed)return {ok:false,status:403,code:"ADMIN_REQUIRED"} as const;return {ok:true,userId:String(u.id)} as const;}
function hit(m:Map<string,Bucket>,k:string,w:number,l:number){const n=Date.now(),b=m.get(k);if(!b||n-b.start>=w){m.set(k,{start:n,count:1});return {allowed:true,retryAfter:0}}b.count++;if(b.count>l)return {allowed:false,retryAfter:Math.max(1,Math.ceil((w-(n-b.start))/1000))};return {allowed:true,retryAfter:0};}
function rate(id:string){const b=hit(burstBuckets,id,10000,15);return b.allowed?hit(minuteBuckets,id,60000,60):b;}
function serviceEnv(){const {url,service}=env();if(!service)throw new Error("service_backend_not_configured");return {url,service};}
async function rest(table:string,params:Record<string,string>){const {url,service}=serviceEnv(),q=new URLSearchParams(params),r=await fetch(`${url}/rest/v1/${table}?${q}`,{headers:{"Authorization":`Bearer ${service}`,"apikey":service,"Accept":"application/json","Accept-Profile":"factory_lite"}});if(!r.ok)throw new Error(`rest_${table}_${r.status}`);return await r.json();}
const stateFrom=(s:string|null)=>s==="PENDING"?"pending":s==="ACCEPTED"?"working":s==="COMPLETED"?"completed":s==="REJECTED"?"blocked":"not_applicable";
function routePath(url:string){const pathname=new URL(url).pathname||"/";for(const prefix of ["/functions/v1/factory","/factory"]){if(pathname===prefix)return "/";if(pathname.startsWith(prefix+"/"))return pathname.slice(prefix.length);}return pathname;}
Deno.serve(async(req:Request)=>{const started=Date.now(),requestId=crypto.randomUUID(),origin=req.headers.get("origin");const path=routePath(req.url);console.log(JSON.stringify({event:"factory_request",method:req.method,origin_present:Boolean(origin),origin_match:!origin||origin===ALLOWED_ORIGIN,path}));const c=cors(req);if(c===null)return json({status:"error",code:"ORIGIN_NOT_ALLOWED",request_id:requestId},403,{"x-request-id":requestId});if(req.method==="OPTIONS")return new Response(null,{status:204,headers:c});if(req.method!=="GET")return json({status:"error",code:"METHOD_NOT_ALLOWED",request_id:requestId},405,{...c,"x-request-id":requestId});let p;try{p=await authenticateAdmin(req)}catch{return json({status:"error",code:"AUTHORIZATION_UNAVAILABLE",request_id:requestId},503,{...c,"x-request-id":requestId})}if(!p.ok)return json({status:"error",code:p.code,request_id:requestId},p.status,{...c,"x-request-id":requestId});const rl=rate(p.userId);if(!rl.allowed)return json({status:"error",code:"RATE_LIMITED",request_id:requestId},429,{...c,"x-request-id":requestId,"Retry-After":String(rl.retryAfter)});try{
if(path==="/summary"){const [agents,work,handoffs]=await Promise.all([rest("agents",{select:"id,status",limit:String(MAX_AGENTS)}),rest("work_items",{select:"id,status,payload",limit:String(MAX_WORK_ITEMS)}),rest("handoffs",{select:"id,status",limit:String(MAX_HANDOFFS)})]);return json({status:"ok",contract_version:CONTRACT_VERSION,summary:{active_agents:agents.filter((x:any)=>x.status==="ACTIVE").length,in_flight_work_items:work.filter((x:any)=>["OPEN","IN_PROGRESS"].includes(x.status)).length,pending_handoffs:handoffs.filter((x:any)=>x.status==="PENDING").length,blocked_work_items:work.filter((x:any)=>explicitTrue(x.payload,"blocked")).length,waiting_for_juancho:work.filter((x:any)=>explicitTrue(x.payload,"waiting_for_juancho")).length,derivation:{blocked:"payload.blocked === true",waiting_for_juancho:"payload.waiting_for_juancho === true"}},request_id:requestId},200,{...c,"x-request-id":requestId});}
if(path==="/board"){
const [work,agents,handoffs,features]=await Promise.all([
rest("work_items",{select:"id,work_key,short_code,title,status,owner_agent_id,current_executor_agent_id,workflow_stage,feature_id,payload,updated_at",order:"updated_at.desc",limit:String(MAX_WORK_ITEMS)}),
rest("agents",{select:"id,code,name,status",order:"code.asc",limit:String(MAX_AGENTS)}),
rest("handoffs",{select:"id,work_item_id,from_agent_id,to_agent_id,status,created_at,accepted_at,completed_at",order:"created_at.asc",limit:String(MAX_HANDOFFS)}),
rest("features",{select:"id,feature_key,short_code,title,product,application,archived",order:"created_at.desc",limit:"200"})]);
return json({status:"ok",contract_version:CONTRACT_VERSION,...buildBoard(work,agents,handoffs,features),limited:work.length>=MAX_WORK_ITEMS||agents.length>=MAX_AGENTS||handoffs.length>=MAX_HANDOFFS||features.length>=200,request_id:requestId},200,{...c,"x-request-id":requestId});}
if(path==="/agents"){const [agents,work,inbox]=await Promise.all([rest("agents",{select:"id,code,name,role,status,created_at",order:"code.asc",limit:String(MAX_AGENTS)}),rest("work_items",{select:"id,work_key,title,status,owner_agent_id,updated_at",limit:String(MAX_WORK_ITEMS)}),rest("agent_inbox",{select:"handoff_id,handoff_status,work_item_id,work_key,work_item_title,target_agent_code,created_at,accepted_at",limit:String(MAX_HANDOFFS)})]);const cards=agents.map((a:any)=>({code:a.code,name:a.name,role:a.role,status:a.status,current_work:work.filter((w:any)=>w.owner_agent_id===a.id&&["OPEN","IN_PROGRESS"].includes(w.status)).map((w:any)=>({work_item_id:w.id,work_key:w.work_key,title:w.title,status:w.status,updated_at:w.updated_at})),inbox:inbox.filter((i:any)=>i.target_agent_code===a.code).map((i:any)=>({handoff_id:i.handoff_id,status:i.handoff_status,work_item_id:i.work_item_id,work_key:i.work_key,title:i.work_item_title,created_at:i.created_at,accepted_at:i.accepted_at}))}));return json({status:"ok",contract_version:CONTRACT_VERSION,agents:cards,request_id:requestId},200,{...c,"x-request-id":requestId});}
const pipe=path.match(/^\/work-items\/([0-9a-f-]{36})\/pipeline$/i);if(pipe){const id=pipe[1],[ws,hs,agents]=await Promise.all([rest("work_items",{select:"id,work_key,title,status,owner_agent_id,payload",id:`eq.${id}`,limit:"1"}),rest("handoffs",{select:"id,from_agent_id,to_agent_id,status,created_at,accepted_at,completed_at,result",work_item_id:`eq.${id}`,order:"created_at.asc",limit:String(MAX_HANDOFFS)}),rest("agents",{select:"id,code,name",limit:String(MAX_AGENTS)})]),w=ws[0];if(!w)return json({status:"error",code:"WORK_ITEM_NOT_FOUND",request_id:requestId},404,{...c,"x-request-id":requestId});const m=new Map(agents.map((a:any)=>[a.id,a]));return json({status:"ok",contract_version:CONTRACT_VERSION,work_item:{id:w.id,work_key:w.work_key,title:w.title,status:w.status,blocked:explicitTrue(w.payload,"blocked"),waiting_for_juancho:explicitTrue(w.payload,"waiting_for_juancho")},pipeline:hs.map((h:any)=>({handoff_id:h.id,from_agent:(m.get(h.from_agent_id) as any)?.code??null,to_agent:(m.get(h.to_agent_id) as any)?.code??null,status:h.status,state:stateFrom(h.status),created_at:h.created_at,accepted_at:h.accepted_at,completed_at:h.completed_at,result_status:h.result?.status??null,result_message:clean(h.result?.message)})),request_id:requestId},200,{...c,"x-request-id":requestId});}
const hist=path.match(/^\/work-items\/([0-9a-f-]{36})\/history$/i);if(hist){const id=hist[1],[ws,events,agents]=await Promise.all([rest("work_items",{select:"id,work_key,title,status,payload",id:`eq.${id}`,limit:"1"}),rest("events",{select:"id,handoff_id,agent_id,event_type,created_at",work_item_id:`eq.${id}`,order:"created_at.asc",limit:String(MAX_EVENTS)}),rest("agents",{select:"id,code",limit:String(MAX_AGENTS)})]),w=ws[0];if(!w)return json({status:"error",code:"WORK_ITEM_NOT_FOUND",request_id:requestId},404,{...c,"x-request-id":requestId});const m=new Map(agents.map((a:any)=>[a.id,a.code]));return json({status:"ok",contract_version:CONTRACT_VERSION,work_item:{id:w.id,work_key:w.work_key,title:w.title,status:w.status,blocked:explicitTrue(w.payload,"blocked"),waiting_for_juancho:explicitTrue(w.payload,"waiting_for_juancho")},history:events.map((e:any)=>({event_id:e.id,handoff_id:e.handoff_id,agent_code:m.get(e.agent_id)??null,event_type:e.event_type,created_at:e.created_at})),request_id:requestId},200,{...c,"x-request-id":requestId});}
return json({status:"error",code:"NOT_FOUND",request_id:requestId},404,{...c,"x-request-id":requestId});
}catch{console.error(JSON.stringify({request_id:requestId,path,status:"error",elapsed_ms:Date.now()-started}));return json({status:"error",code:"FACTORY_READ_FAILED",request_id:requestId},500,{...c,"x-request-id":requestId})}});

