import { FormEvent, useEffect, useMemo, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { getAgents,getBoard,getHistory,getPipeline,getSummary,supabase } from './api'
import type { BoardData } from './contracts'

type Page='overview'|'board'|'pipelines'|'agents'|'blockers'|'history'
const labels:Record<Page,string>={overview:'Overview',board:'Board',pipelines:'Pipelines',agents:'Agents',blockers:'Blockers',history:'History'}
const stateMeta={blocked:['!','Blocked'],working:['●','Working'],pending:['→','Pending'],completed:['✓','Completed'],not_applicable:['·','N/A']} as const
const fmt=(v:string|null|undefined)=>v?new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—'

function Login(){
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);setBusy(false)}
 return <main className="login"><section className="login-card"><span className="eyebrow">AGENT FACTORY</span><h1>Factory Control</h1><p>Acceso administrativo. La aplicación es de solo lectura.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username"/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label>{error&&<div className="error-banner">{error}</div>}<button disabled={busy}>{busy?'Accediendo…':'Acceder'}</button></form></section></main>
}

function Kpi({label,value,hot,onClick}:{label:string,value:number,hot?:boolean,onClick?:()=>void}){return <button className={`kpi ${hot?'hot':''}`} onClick={onClick}><strong>{value}</strong><span>{label}</span></button>}
function StatusPill({state}:{state:keyof typeof stateMeta}){const [symbol,label]=stateMeta[state];return <span className={`status state-${state}`} aria-label={label}><b>{symbol}</b>{label}</span>}

function Board({data,onOpen,compact=false}:{data:BoardData,onOpen:(id:string)=>void,compact?:boolean}){
 const [q,setQ]=useState(''); const rows=data.rows.filter(r=>(r.work_key+' '+r.title).toLowerCase().includes(q.toLowerCase())).slice(0,compact?6:999)
 return <section className="panel"><div className="section-head"><div><h2>{compact?'Active work':'Factory Board'}</h2><p>Quién trabaja en qué y qué handoff viene después.</p></div>{!compact&&<input className="search" placeholder="Buscar work item…" value={q} onChange={e=>setQ(e.target.value)}/>}</div><div className="board-desktop"><table><thead><tr><th className="sticky-col">Work item</th>{data.agents.map(a=><th key={a.code}><span>{a.code}</span><small>{a.status}</small></th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.work_item_id}><th className="sticky-col"><button className="work-link" onClick={()=>onOpen(r.work_item_id)}><b>{r.work_key}</b><span>{r.title}</span><small>{r.status}{r.waiting_for_juancho?' · Waiting Juancho':''}</small></button></th>{data.agents.map(a=>{const c=r.cells.find(x=>x.agent_code===a.code); const s=c?.state??'not_applicable';return <td key={a.code} title={c?.latest_handoff_id||undefined}><StatusPill state={s}/>{c&&(c.origin||c.destination)&&<small className="flow">{c.origin?'FROM':''}{c.origin&&c.destination?' / ':''}{c.destination?'TO':''}</small>}</td>})}</tr>)}</tbody></table></div><div className="board-mobile">{rows.map(r=><button className="work-card" key={r.work_item_id} onClick={()=>onOpen(r.work_item_id)}><div><b>{r.work_key}</b><span>{r.status}</span></div><strong>{r.title}</strong><div className="participation">{r.cells.map(c=><span key={`${r.work_item_id}-${c.agent_code}`}><StatusPill state={c.state}/><small>{c.agent_code}</small></span>)}</div>{r.waiting_for_juancho&&<em>Waiting for Juancho</em>}</button>)}</div>{rows.length===0&&<div className="empty">No matching work items.</div>}</section>
}

function Pipeline({id}:{id:string}){const q=useQuery({queryKey:['pipeline',id],queryFn:()=>getPipeline(id),enabled:!!id});if(q.isLoading)return <div className="skeleton">Loading pipeline…</div>;if(q.error)return <ErrorBox error={q.error}/>;if(!q.data)return null;return <section className="panel"><div className="section-head"><div><h2>{q.data.work_item.work_key}</h2><p>{q.data.work_item.title} · {q.data.work_item.status}</p></div>{q.data.work_item.waiting_for_juancho&&<span className="attention">Waiting for Juancho</span>}</div><div className="pipeline">{q.data.pipeline.length?q.data.pipeline.map((n,i)=><article className={`node state-${n.state}`} key={n.handoff_id}><div className="node-top"><StatusPill state={n.state}/><small>#{i+1}</small></div><h3>{n.from_agent||'—'} <span>→</span> {n.to_agent||'—'}</h3><p>{n.status}</p><dl><dt>Created</dt><dd>{fmt(n.created_at)}</dd><dt>Accepted</dt><dd>{fmt(n.accepted_at)}</dd><dt>Completed</dt><dd>{fmt(n.completed_at)}</dd></dl>{n.result_status&&<div className="result"><b>{n.result_status}</b>{n.result_message&&<span>{n.result_message}</span>}</div>}<small>{n.handoff_id}</small></article>):<div className="empty">No handoffs for this work item.</div>}</div></section>}
function ErrorBox({error}:{error:unknown}){return <div className="error-banner">{error instanceof Error?error.message:'Could not load Factory Lite.'}</div>}

export default function App(){
 const [sessionReady,setSessionReady]=useState(false); const [authenticated,setAuthenticated]=useState(false); const [page,setPage]=useState<Page>('overview'); const [selected,setSelected]=useState(''); const qc=useQueryClient()
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setAuthenticated(!!data.session);setSessionReady(true)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setAuthenticated(!!s));return()=>subscription.unsubscribe()},[])
 const summary=useQuery({queryKey:['summary'],queryFn:getSummary,enabled:authenticated}); const board=useQuery({queryKey:['board'],queryFn:getBoard,enabled:authenticated}); const agents=useQuery({queryKey:['agents'],queryFn:getAgents,enabled:authenticated});
 useEffect(()=>{if(!selected&&board.data?.rows[0])setSelected(board.data.rows[0].work_item_id)},[board.data,selected])
 const history=useQuery({queryKey:['history',selected],queryFn:()=>getHistory(selected),enabled:authenticated&&!!selected});
 const lastUpdated=Math.max(summary.dataUpdatedAt,board.dataUpdatedAt,agents.dataUpdatedAt,history.dataUpdatedAt||0)
 const waiting=board.data?.rows.filter(r=>r.waiting_for_juancho)??[]; const blocked=board.data?.rows.filter(r=>r.blocked)??[]
 const refresh=()=>qc.invalidateQueries()
 if(!sessionReady)return <main className="loading-screen">Loading Factory Control…</main>; if(!authenticated)return <Login/>
 const openPipeline=(id:string)=>{setSelected(id);setPage('pipelines')}
 const content=()=>{
  if(summary.error||board.error||agents.error)return <ErrorBox error={summary.error||board.error||agents.error}/>
  if(summary.isLoading||board.isLoading||agents.isLoading)return <div className="skeleton large">Loading Factory Lite…</div>
  if(!summary.data||!board.data||!agents.data)return null
  if(page==='overview')return <><div className="kpis"><Kpi label="Active agents" value={summary.data.summary.active_agents} onClick={()=>setPage('agents')}/><Kpi label="In flight" value={summary.data.summary.in_flight_work_items} onClick={()=>setPage('board')}/><Kpi label="Pending handoffs" value={summary.data.summary.pending_handoffs} onClick={()=>setPage('board')}/><Kpi label="Blocked" value={summary.data.summary.blocked_work_items} hot={summary.data.summary.blocked_work_items>0} onClick={()=>setPage('blockers')}/><Kpi label="Waiting for Juancho" value={summary.data.summary.waiting_for_juancho} hot={summary.data.summary.waiting_for_juancho>0} onClick={()=>setPage('blockers')}/></div><div className="overview-grid"><Board data={board.data} onOpen={openPipeline} compact/><section className="panel blockers"><h2>Waiting / Blockers</h2>{waiting.map(r=><button key={r.work_item_id} onClick={()=>openPipeline(r.work_item_id)}><b>{r.work_key}</b><span>Waiting for Juancho</span></button>)}{blocked.filter(r=>!r.waiting_for_juancho).map(r=><button key={r.work_item_id} onClick={()=>openPipeline(r.work_item_id)}><b>{r.work_key}</b><span>Blocked</span></button>)}{!waiting.length&&!blocked.length&&<div className="empty">No blockers. Nothing is waiting for Juancho.</div>}</section></div>{selected&&history.data&&<HistoryPanel data={history.data.history.slice(-8).reverse()}/>}</>
  if(page==='board')return <Board data={board.data} onOpen={openPipeline}/>
  if(page==='pipelines')return <><WorkPicker rows={board.data.rows} selected={selected} setSelected={setSelected}/>{selected&&<Pipeline id={selected}/>}</>
  if(page==='agents')return <section className="panel"><div className="section-head"><div><h2>Agents</h2><p>Estado, trabajo actual e inbox.</p></div></div><div className="agents-grid">{agents.data.agents.map(a=><article className="agent-card" key={a.code}><div className="agent-head"><div><h3>{a.name}</h3><code>{a.code}</code></div><span className={`agent-state ${a.status==='ACTIVE'?'active':''}`}>{a.status}</span></div><p>{a.role}</p><h4>Current work</h4>{a.current_work.length?a.current_work.map(w=><button key={w.work_item_id} onClick={()=>openPipeline(w.work_item_id)}><b>{w.work_key}</b><span>{w.title}</span></button>):<small>No active work.</small>}<h4>Inbox</h4><div className="inbox-counts"><span>Pending {a.inbox.filter(i=>i.status==='PENDING').length}</span><span>Accepted {a.inbox.filter(i=>i.status==='ACCEPTED').length}</span></div></article>)}</div></section>
  if(page==='blockers')return <section className="panel"><div className="section-head"><div><h2>Blockers</h2><p>Acciones externas y bloqueos explícitos.</p></div></div><h3>Waiting for Juancho</h3><div className="list">{waiting.map(r=><button key={r.work_item_id} onClick={()=>openPipeline(r.work_item_id)}><b>{r.work_key}</b><span>{r.title}</span><em>{fmt(r.updated_at)}</em></button>)}{!waiting.length&&<div className="empty">Nothing is waiting for Juancho.</div>}</div><h3>Other blockers</h3><div className="list">{blocked.filter(r=>!r.waiting_for_juancho).map(r=><button key={r.work_item_id} onClick={()=>openPipeline(r.work_item_id)}><b>{r.work_key}</b><span>{r.title}</span><em>{fmt(r.updated_at)}</em></button>)}{!blocked.filter(r=>!r.waiting_for_juancho).length&&<div className="empty">No other blockers.</div>}</div></section>
  return <><WorkPicker rows={board.data.rows} selected={selected} setSelected={setSelected}/>{history.isLoading?<div className="skeleton">Loading history…</div>:history.error?<ErrorBox error={history.error}/>:history.data?<section className="panel"><div className="section-head"><div><h2>History</h2><p>{history.data.work_item.work_key} · {history.data.work_item.title}</p></div></div><HistoryPanel data={history.data.history.slice().reverse()}/></section>:null}</>
 }
 return <div className="app-shell"><aside><div className="brand"><span>AF</span><div><b>Factory Control</b><small>Agent Factory</small></div></div><nav>{(Object.keys(labels) as Page[]).map(p=><button className={page===p?'active':''} key={p} onClick={()=>setPage(p)}>{labels[p]}</button>)}</nav><div className="side-foot"><span>READ ONLY</span><button onClick={()=>supabase.auth.signOut()}>Sign out</button></div></aside><main><header><div><span className="eyebrow">FACTORY CONTROL</span><h1>{labels[page]}</h1></div><div className="header-actions"><small>Last refresh {lastUpdated?new Date(lastUpdated).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}):'—'}</small><button onClick={refresh}>Refresh</button><span>READ ONLY</span></div></header><div className="content">{content()}</div></main><nav className="bottom-nav">{(['overview','board','agents','blockers'] as Page[]).map(p=><button className={page===p?'active':''} key={p} onClick={()=>setPage(p)}>{labels[p]}</button>)}</nav></div>
}
function WorkPicker({rows,selected,setSelected}:{rows:BoardData['rows'];selected:string;setSelected:(v:string)=>void}){return <label className="picker">Work item<select value={selected} onChange={e=>setSelected(e.target.value)}>{rows.map(r=><option key={r.work_item_id} value={r.work_item_id}>{r.work_key} · {r.title}</option>)}</select></label>}
function HistoryPanel({data}:{data:Array<{event_id:number;handoff_id:string|null;agent_code:string|null;event_type:string;created_at:string}>}){const [q,setQ]=useState('');const filtered=useMemo(()=>data.filter(e=>`${e.agent_code} ${e.event_type} ${e.handoff_id}`.toLowerCase().includes(q.toLowerCase())),[data,q]);return <section className="history"><div className="section-head"><h2>Recent activity</h2><input className="search" placeholder="Search history…" value={q} onChange={e=>setQ(e.target.value)}/></div>{filtered.map(e=><article key={e.event_id}><time>{fmt(e.created_at)}</time><b>{e.agent_code||'SYSTEM'}</b><span>{e.event_type}</span>{e.handoff_id&&<code>{e.handoff_id.slice(0,8)}</code>}</article>)}{!filtered.length&&<div className="empty">No history events.</div>}</section>}
