import { z } from 'zod'

export const cellState = z.enum(['blocked','working','pending','completed','not_applicable'])
export const summaryResponse = z.object({status:z.literal('ok'),contract_version:z.literal('factory-control-read-v0.1.1'),summary:z.object({active_agents:z.number(),in_flight_work_items:z.number(),pending_handoffs:z.number(),blocked_work_items:z.number(),waiting_for_juancho:z.number(),derivation:z.object({blocked:z.string(),waiting_for_juancho:z.string()})}),request_id:z.string()})
export const boardCell = z.object({agent_code:z.string().nullable(),state:cellState,latest_handoff_id:z.string().uuid().nullable(),origin:z.boolean(),destination:z.boolean()})
export const boardResponse = z.object({status:z.literal('ok'),contract_version:z.literal('factory-control-read-v0.1.1'),agents:z.array(z.object({code:z.string(),name:z.string(),status:z.string()})),rows:z.array(z.object({work_item_id:z.string().uuid(),work_key:z.string(),title:z.string(),status:z.string(),owner_agent_code:z.string().nullable(),blocked:z.boolean(),waiting_for_juancho:z.boolean(),updated_at:z.string().nullable(),cells:z.array(boardCell)})),request_id:z.string()})
export const agentsResponse = z.object({status:z.literal('ok'),contract_version:z.literal('factory-control-read-v0.1.1'),agents:z.array(z.object({code:z.string(),name:z.string(),role:z.string(),status:z.string(),current_work:z.array(z.object({work_item_id:z.string().uuid(),work_key:z.string(),title:z.string(),status:z.string(),updated_at:z.string().nullable()})),inbox:z.array(z.object({handoff_id:z.string().uuid(),status:z.string(),work_item_id:z.string().uuid(),work_key:z.string(),title:z.string(),created_at:z.string().nullable(),accepted_at:z.string().nullable()}))})),request_id:z.string()})
const workItem = z.object({id:z.string().uuid(),work_key:z.string(),title:z.string(),status:z.string(),blocked:z.boolean(),waiting_for_juancho:z.boolean()})
export const pipelineResponse = z.object({status:z.literal('ok'),contract_version:z.literal('factory-control-read-v0.1.1'),work_item:workItem,pipeline:z.array(z.object({handoff_id:z.string().uuid(),from_agent:z.string().nullable(),to_agent:z.string().nullable(),status:z.string(),state:cellState,created_at:z.string().nullable(),accepted_at:z.string().nullable(),completed_at:z.string().nullable(),result_status:z.string().nullable(),result_message:z.string().nullable()})),request_id:z.string()})
export const historyResponse = z.object({status:z.literal('ok'),contract_version:z.literal('factory-control-read-v0.1.1'),work_item:workItem,history:z.array(z.object({event_id:z.number(),handoff_id:z.string().uuid().nullable(),agent_code:z.string().nullable(),event_type:z.string(),created_at:z.string()})),request_id:z.string()})
export type BoardData=z.infer<typeof boardResponse>; export type AgentsData=z.infer<typeof agentsResponse>; export type PipelineData=z.infer<typeof pipelineResponse>; export type HistoryData=z.infer<typeof historyResponse>;
